### ISSUE TITLE
configuration.yaml doesn't like hostname as option.

### ISSUE THREAD

**Issue by Smith754** [Poeschl/ha-picoTTS_remote#1]
Invalid config for [tts.picotts]: [hostname] is an invalid option for [tts.picotts]. Check: tts.picotts->hostname. (See ?, line ?). Please check the docs at https://home-assistant.io/components/tts.picotts/

Tried to use your "remote picoTTS Home Assistant Component" but configuration.yaml doesn't like hostname as option.  Probably wont like port either. They aren't options listed on picotts page on home assistant website:  https://www.home-assistant.io/components/picotts/

Is this supposed to go somewhere other than configuration.yaml?
tts:
  - platform: picotts                              
    language: 'en-US'
    hostname: 'localhost'
    port: 59126

P.S. Thanks for all your work. The Mary TTS for hassio works great. Although it only has American voice. Can't make it do any others. Anyways, kudos!

Hassio in docker on Intel Nuc, using Linux Mint.

**Comment by Poeschl** [comment]
Wuppsi, I missed the '_remote' suffix of the platform specifier.

To use the remote Pico and not the embedded one the configuration.yaml should contain
```
tts:
- platform: picotts_remote
  language: 'en-US'
  hostname: 'localhost'
  port: 59126
```

Thanks for the issue 🙏, fixed it in the readme

**Comment by Poeschl** [comment]
PS: the MaryTTS should do also other voices via the `language` config. Tested it with german. If not, feel free to open an issue there.

**Comment by Smith754** [comment]
Got it working!  Home Assistant still didn't like "hostname:" so I changed it to "host:" and it seems to work fine now.

tts:
 - platform: picotts_remote
    language: 'en-US'
    host: 'localhost'
    port: 59126

**Comment by Poeschl** [comment]
👍 Very nice. I adjusted the example in the config.

Feel free to close the issue.
