### ISSUE TITLE
PicoTTS service stopped working after Home Assistant update 

### ISSUE THREAD

**Issue by noisemaker00** [Poeschl/ha-picoTTS_remote#6]
After the updating Home Assistant to core-2021.8.8 and Home Assistant OS to 6.2 the PicoTTS service does not work anymore.
The home assistant logs report the integrations fails.

**Comment by Poeschl** [comment]
@noisemaker00 Can you provide the log of the home assistant startup with the failure of the integration?

**Comment by noisemaker00** [comment]
I found this in the log, maybe the cause of the issue?
`ERROR (SyncWorker_0) [homeassistant.loader] The custom integration 'picotts_remote' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by Poeschl** [comment]
That looks like it. I will take a closer look the next days. I'm currently away from home.

Are you using version 1.0.1 of the integration?

**Comment by Poeschl** [comment]
Issue closed due to inactivity.
